   console.log('JS Lesson 1'); 
let model = 'Porsche 992 GT3';
let color = 'black';
let price = '15000000000';
let year = 2000;
let goodcar = 'true';
let turbocar = 'true';
let nicecar = 'true';
let fastcar = 'true';
let expensivecar = 'true';
let cheap = 'false';
let country = 'Germany';
let maxspeed = 320;
let popular = 'true';
let bad = 'false';
let force = 'true';
let gasoline = 3996;
let сylinderarrangement = 'opposite';
let cylinders = 6;
let valves = 24;
let compressionratio = 13.3-1;
let engine = '4.0i';
let disks = 'forged';
let audiosystem = 'Sound Package Plus';
let sportcar = 'true';
let coolcar = 'true';
let electricalequipment = 'true';
let slowcar = 'false';
let inventor ='Fedinand Porsche';
let data = 30.01;
let datayear = 1951;
let madein = 'Stuttgart';
let highqualitymaterials = 'true';
let availability = 'is availability';
let headlights = 'true';
let metal = 'true';
let glass = 'true';
let mirror = 'true';
let seats = 'true';
let trunk = 'true';
let door = 'true';
let panel = 'true';
let steeringwheel = 'true';
let pedals = 'true';
let thrombosis = 'true';
let windows = 'true';
let bumper = 'true';
let transmission = 'true';
let music = 'true';
let discs = 'true';
let wheels = 'true';


console.log(model);
console.log(color);
console.log(price);
console.log(year);
console.log(goodcar);
console.log(turbocar);
console.log(nicecar);
console.log(fastcar);
console.log(expensivecar);
console.log(cheap);
console.log(country);
console.log(maxspeed);
console.log(popular);
console.log(bad);
console.log(force);
console.log(gasoline);
console.log(сylinderarrangement);
console.log(cylinders);
console.log(valves);
console.log(compressionratio);
console.log(engine);
console.log(disks);
console.log(audiosystem);
console.log(sportcar);
console.log(coolcar);
console.log(electricalequipment);
console.log(slowcar);
console.log(inventor);
console.log(data);
console.log(datayear);
console.log(madein);
console.log(highqualitymaterials);
console.log(availability);
console.log(headlights);
console.log(metal);
console.log(glass);
console.log(mirror);
console.log(seats);
console.log(trunk);
console.log(door);
console.log(panel);
console.log(steeringwheel);
console.log(pedals);
console.log(thrombosis);
console.log(windows);
console.log(bumper);
console.log(transmission);
console.log(music);
console.log(discs);
console.log(wheels);